# Introduce with numpy

In [2]:
import numpy as np
print(np.__version__)

1.20.1


In [3]:
a = np.array([1,2,3,4,5], dtype=np.int8)

In [4]:
a

array([1, 2, 3, 4, 5], dtype=int8)

In [6]:
a[[0,3]]

array([1, 4], dtype=int8)

In [7]:
a[:4]

array([1, 2, 3, 4], dtype=int8)

In [8]:
a[:3]

array([1, 2, 3], dtype=int8)

In [11]:
b = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
], dtype=np.int8)

In [12]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int8)

In [13]:
b[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]], dtype=int8)

In [14]:
b[:2,:2
]

array([[1, 2],
       [4, 5]], dtype=int8)

In [15]:
b.dtype

dtype('int8')

In [16]:
b.shape

(3, 3)

In [19]:
b.ndim

2

In [20]:
a.ndim

1

In [21]:
a.size

5

In [22]:
b.size

9

In [23]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int8)

In [24]:
b[0] = 5

In [25]:
b

array([[5, 5, 5],
       [4, 5, 6],
       [7, 8, 9]], dtype=int8)

In [26]:
b[0,1] = 9

In [27]:
b

array([[5, 9, 5],
       [4, 5, 6],
       [7, 8, 9]], dtype=int8)

In [29]:
c = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
],dtype=np.int8)

In [30]:
c.sum()

45

In [31]:
c.mean()

5.0

In [32]:
c.std()

2.581988897471611

In [33]:
c.size

9

In [35]:
c.size

9

In [36]:
c.mean(axis=0)

array([4., 5., 6.])

In [37]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int8)

In [38]:
c.mean(axis=1)

array([2., 5., 8.])

In [39]:
c.sum(axis=0)

array([12, 15, 18])

In [40]:
c.sum(axis=1)

array([ 6, 15, 24])

In [41]:
c.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [42]:
c.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [43]:
a = np.array([1,2,3,4,5,6,7,8,9], dtype = np.int8)

In [44]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)

In [45]:
a + 10

array([11, 12, 13, 14, 15, 16, 17, 18, 19], dtype=int8)

In [46]:
a *10

array([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=int8)

In [47]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)

In [48]:
a += 10

In [49]:
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19], dtype=int8)

In [51]:
a -= 10

In [52]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)

In [63]:
b = np.arange(9)

In [64]:
b[:] = 5 

In [65]:
b

array([5, 5, 5, 5, 5, 5, 5, 5, 5])

In [66]:
a + b

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [67]:
a * b

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [72]:
a = np.arange(1,4,2)

In [73]:
a

array([1, 3])

In [74]:
a = np.array([
    np.arange(2),
    np.arange(2),
    np.arange(2),
])

In [75]:
a

array([[0, 1],
       [0, 1],
       [0, 1]])

In [76]:
a = a[:2,:]

In [77]:
a

array([[0, 1],
       [0, 1]])

In [80]:
b = np.array([
    np.arange(5,7),
    np.arange(3,5),
])

In [81]:
b

array([[5, 6],
       [3, 4]])

In [82]:
a +b 

array([[5, 7],
       [3, 5]])

In [83]:
a * b

array([[0, 6],
       [0, 4]])

In [85]:
a = np.arange(1,10)

In [86]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
a > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [88]:
a % 2 == 0

array([False,  True, False,  True, False,  True, False,  True, False])

In [89]:
a[a%2==0]

array([2, 4, 6, 8])

In [93]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
b = np.random.randint(0,100,size=(3,3))

In [95]:
b

array([[95, 85, 54],
       [81, 37, 14],
       [52, 45, 11]])

In [97]:
b > 50

array([[ True,  True,  True],
       [ True, False, False],
       [ True, False, False]])

In [98]:
b[b>50]

array([95, 85, 54, 81, 52])

In [99]:
b[~(b>50)]

array([37, 14, 45, 11])

In [100]:
b[(b%2==0) & (b>50)]

array([54, 52])

In [103]:
b.ndim

2

In [104]:
b.shape

(3, 3)

In [108]:
b[:,[1]]

array([[85],
       [37],
       [45]])

In [109]:
b

array([[95, 85, 54],
       [81, 37, 14],
       [52, 45, 11]])

In [110]:
b[[0],[0]]

array([95])

## ------------

In [113]:
A = np.reshape([1,2,3,4,5,6,7,8,9],(3,3))

In [114]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [115]:
B = np.reshape([1,2,3,4,5,6],(3,2))

In [116]:
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [117]:
A.dot(B)

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

In [118]:
C = np.arange(1,10)

In [119]:
D = np.arange(1,5)

In [122]:
C*D

ValueError: operands could not be broadcast together with shapes (9,) (4,) 

In [123]:
A @ B

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

In [124]:
B @ A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [126]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [127]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [128]:
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [129]:
B.T

array([[1, 3, 5],
       [2, 4, 6]])

In [130]:
%time

Wall time: 0 ns


In [133]:
%time np.sum(np.arange(100000))

Wall time: 999 µs


704982704

In [134]:
%time sum(list(range(100000)))

Wall time: 4 ms


4999950000

In [144]:
%time np.sum(np.arange(1000000) ** 2)

Wall time: 6 ms


584144992

In [164]:
%time sum((x**2 for x in range(1000000)))

Wall time: 357 ms


333332833333500000

In [171]:
%time sum([x**2 for x in range(1000000)])

Wall time: 383 ms


333332833333500000

In [172]:
np.random.random()

0.019821893840910487

In [173]:
np.random.random(size=4)

array([0.77263878, 0.68426018, 0.19949228, 0.44518329])

In [174]:
np.random.normal()

-1.2922948086798252

In [177]:
np.random.normal(size=10)

array([-0.83262167,  0.02884841, -1.67229714,  0.59075025, -0.21500335,
       -2.7192424 , -0.1320762 ,  0.70820537,  0.65725359, -0.21548511])

In [178]:
np.random.rand()

0.7959266533146039

In [179]:
np.random.rand(2)

array([0.4205498 , 0.99554492])

In [180]:
np.random.rand(2,5)

array([[0.74205081, 0.05259156, 0.01268976, 0.75310053, 0.58302243],
       [0.65364665, 0.47612455, 0.60761945, 0.68973342, 0.26461809]])

In [183]:
np.random.random(2,2)

TypeError: random() takes at most 1 positional argument (2 given)

In [186]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [188]:
np.linspace(0,20,20)

array([ 0.        ,  1.05263158,  2.10526316,  3.15789474,  4.21052632,
        5.26315789,  6.31578947,  7.36842105,  8.42105263,  9.47368421,
       10.52631579, 11.57894737, 12.63157895, 13.68421053, 14.73684211,
       15.78947368, 16.84210526, 17.89473684, 18.94736842, 20.        ])

In [189]:
np.linspace(0,1,20,False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [190]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [191]:
np.linspace(0,20,20, False)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [193]:
#cool

In [195]:
np.zeros(5)
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [196]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [197]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [199]:
np.ones((4,4),dtype=np.int8)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [200]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [203]:
np.empty((3,3,3), dtype=np.int)

<ipython-input-203-0274c0a290f6>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.empty((3,3,3), dtype=np.int)


array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [204]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

In [205]:
np.empty((3, 3))

array([[1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.]])

In [206]:
np.empty((1, 1))

array([[1.]])

In [207]:
np.empty((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [208]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [209]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [210]:
np.identity(3,4)

TypeError: Cannot interpret '4' as a data type

In [211]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [212]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [213]:
'YA LOX'[4]

'O'