# `Ex_2` dawn

In [1]:
import numpy as np
print(np.__version__)

1.20.1


In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [9]:
np.ones((2,2), dtype=np.int)

<ipython-input-9-57ccc1f8b31f>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones((2,2), dtype=np.int)


array([[1, 1],
       [1, 1]])

In [11]:
np.ones((3,2), dtype=np.float)

<ipython-input-11-dd2361f02787>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones((3,2), dtype=np.float)


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
A = np.arange(0,11,2, dtype=np.int8)

In [21]:
A.dtype 
A

array([ 0,  2,  4,  6,  8, 10], dtype=int8)

In [22]:
B = A.reshape(3,2)

In [23]:
B

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]], dtype=int8)

In [24]:
A = np.ones_like(A)

In [25]:
A

array([1, 1, 1, 1, 1, 1], dtype=int8)

In [31]:
C = np.reshape([1,2,3,4,5,6,7,8,9], (3,3))

In [32]:
C

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
np.zeros_like(C)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [35]:
np.ones((4,4), dtype=np.int)*5

<ipython-input-35-98f488cf6b52>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones((4,4), dtype=np.int)*5


array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [43]:
C = np.reshape([1,2,3,4,5,6,7,8,9], (3,3))

In [47]:
C

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
C[:,:]=7

In [49]:
C

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [56]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
A = np.random.randint(1,11, size=3)
A

array([3, 6, 9])

In [65]:
A = np.random.rand(3,3,3)
A

array([[[0.20458461, 0.77692702, 0.36369016],
        [0.07191528, 0.17187434, 0.26539798],
        [0.24480013, 0.81333484, 0.25917672]],

       [[0.67913433, 0.85729921, 0.51987753],
        [0.30921281, 0.54845513, 0.01291565],
        [0.24142891, 0.15487594, 0.28391661]],

       [[0.82468968, 0.34611361, 0.20981266],
        [0.78746916, 0.47727688, 0.17858615],
        [0.69131693, 0.20267963, 0.74729379]]])

In [66]:
a = [1,2,3,4,5,6]


In [71]:
b = np.reshape(a, (2,3))

In [72]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
c = np.array(a)

In [74]:
c

array([1, 2, 3, 4, 5, 6])

In [75]:
a = np.arange(10)

In [76]:
b = a.copy()

In [77]:
id(a)

1916728064208

In [78]:
id(b)

1916728062192

In [79]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [83]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [84]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [88]:
Z = np.eye(3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [89]:
print('bytes {}'.format(Z.size * Z.itemsize))

bytes 72


In [90]:
Z.size

9

In [91]:
Z.itemsize

8

In [97]:
C = np.arange(5,10)

In [98]:
C[0]

5

In [99]:
C[-1]

9

In [100]:
C[:3]

array([5, 6, 7])

In [101]:
C[1:-1]

array([6, 7, 8])

In [102]:
C[::-1]

array([9, 8, 7, 6, 5])

In [103]:
C[::2]

array([5, 7, 9])

In [106]:
A = np.arange(9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [108]:
A[0,:]

array([0, 1, 2])

In [110]:
A[-1,:]

array([6, 7, 8])

In [111]:
A[0,0]

0

In [112]:
A[-1,-1]

8

In [113]:
A

array([], shape=(0, 3), dtype=int32)

In [115]:
A = np.arange(16).reshape(4,4)

In [116]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [117]:
A[1:-1]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [118]:
A[0:2, 0:2]

array([[0, 1],
       [4, 5]])

In [124]:
A.shape

(4, 4)

In [125]:
A[2:,2:]

array([[10, 11],
       [14, 15]])

In [130]:
A = np.array(A, np.float)

<ipython-input-130-29d3e94ce973>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  A = np.array(A, np.float)


In [131]:
A

array([[2.12199579e-314, 6.36598737e-314],
       [1.06099790e-313, 1.48539705e-313],
       [1.90979621e-313, 2.33419537e-313],
       [2.75859453e-313, 3.18299369e-313]])

In [132]:
c = np.arange(5)

In [133]:
c

array([0, 1, 2, 3, 4])

In [134]:
c = c[::-1]

In [135]:
c

array([4, 3, 2, 1, 0])

In [139]:
d = np.random.randint(0,10,5)

In [140]:
d

array([5, 6, 3, 1, 9])

In [141]:
d.sort()

In [142]:
d

array([1, 3, 5, 6, 9])

In [143]:
d[3] = 1

In [144]:
d

array([1, 3, 5, 1, 9])

In [145]:
A

array([[2.12199579e-314, 6.36598737e-314],
       [1.06099790e-313, 1.48539705e-313],
       [1.90979621e-313, 2.33419537e-313],
       [2.75859453e-313, 3.18299369e-313]])

In [146]:
A[-1,:]= 1

In [147]:
A

array([[2.12199579e-314, 6.36598737e-314],
       [1.06099790e-313, 1.48539705e-313],
       [1.90979621e-313, 2.33419537e-313],
       [1.00000000e+000, 1.00000000e+000]])

In [148]:
A[-1,-1]=0

In [149]:
A

array([[2.12199579e-314, 6.36598737e-314],
       [1.06099790e-313, 1.48539705e-313],
       [1.90979621e-313, 2.33419537e-313],
       [1.00000000e+000, 0.00000000e+000]])

In [150]:
A = A+5

In [151]:
A

array([[5., 5.],
       [5., 5.],
       [5., 5.],
       [6., 5.]])

In [152]:
d

array([1, 3, 5, 1, 9])

In [153]:
d[d<0]

array([], dtype=int32)

In [154]:
d

array([1, 3, 5, 1, 9])

In [155]:
d<0

array([False, False, False, False, False])

In [156]:
z = d[d > 5]

In [157]:
z

array([9])

In [158]:
z = d[d > d.mean()]
z

array([5, 9])

In [159]:
d.mean()

3.8

In [161]:
z = d[(d == 2) | (d == 10)]
z

array([], dtype=int32)

In [162]:
d

array([1, 3, 5, 1, 9])

In [163]:
d.all()

True

In [164]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [165]:
a.all()

False

In [166]:
a.any()

True

In [169]:
~a.all()

True

In [170]:
a.sum()

45

In [171]:
a.mean()

4.5

In [172]:
a.std()

2.8722813232690143

In [173]:
a.var()

8.25

In [174]:
a.sum(axis=0)

45

In [176]:
A

array([[5., 5.],
       [5., 5.],
       [5., 5.],
       [6., 5.]])

In [178]:
A.sum(axis=1)

array([10., 10., 10., 11.])

In [179]:
A.mean(axis=1)

array([5. , 5. , 5. , 5.5])

In [180]:
A.max()

6.0